### ISSUE TITLE
non-functionaltest

### ISSUE THREAD

**Issue by gyuturn** [Nan-Sso-Gong/BlocKing#5]
# 1. 게임 진행의 흐름이 끊기지 않고 원활한가?
- dev1.1 버전에서는 다음블록이 생성되기 까지 3~4 정도의 시간이 소요됨 81ac5f75aaf517adc775ba59bbff36812d8a4514
![캡처](https://user-images.githubusercontent.com/87477702/164537910-da23e6fe-066f-4237-8a1b-2a633343b420.PNG)

- 블럭 생성 후, 다음 블록 생성까지 2초 이내로 생성되도록 수정 
- 재귀를 통해 시간단축
e9ffba96488686254f2446de8f860c8d4c16f2d5

![캡처](https://user-images.githubusercontent.com/87477702/164538082-be392570-f35b-4ea2-ab95-394c4d837dbc.PNG)

# 2. 블록 착지 이후 바로 블럭이 생기지 않고 끼워넣기가 가능한가?
- 사용자의 편의성을 위해 1내의 시긴이 필요하다고 판단
- 블럭 착지 이후 최초 1초에 한하여 이동 가능 
4b2012978b78861a0de454251ce6a6840ebca3df

# 3.사용자의 즐거움을 만족하기 위해 scoreboard에 이모티콘을 추가함

**Comment by gyuturn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [non functional test](https://trello.com/c/ZHVnmlil/147-non-functional-test)

**Comment by oeccsy** [comment]
- 현재 모두 반영된 상태로 issue close 합니다.
