### ISSUE TITLE
GameLogic - 블록이 허공에서 멈춤

### ISSUE THREAD

**Issue by oeccsy** [Nan-Sso-Gong/BlocKing#85]
## 재현 환경
- dev 3.1

## 재현 과정
- 블럭이 바닥에 닿은 후 빠르게 양옆으로 이동

## 오류 내용
- 블럭 아래로 갈 수 있음에도 허공에서 멈춤

## 기대 결과
- 이동 가능성을 다시 검사하여 아래로 이동

## 재현 빈도
- 타이밍에 따라 발생

## 기타자료
- 첨부사진 : 
![image](https://user-images.githubusercontent.com/77562357/169428241-e4678078-4456-4022-b34d-e8ed11f80c69.png)

**Comment by gyuturn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring](https://trello.com/c/9ycY6Zjj/216-refactoring)

**Comment by oeccsy** [comment]
8ba6450b075413c8ffd868901f9f99f7c51cf173 에서 수정하였습니다.
