### ISSUE TITLE
GameUI- 다음으로 버튼

### ISSUE THREAD

**Issue by gyuturn** [Nan-Sso-Gong/BlocKing#89]
다음으로 버튼 삭제(필요없는 기능임)

**Comment by gyuturn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring](https://trello.com/c/9ycY6Zjj/216-refactoring)

**Comment by wooka000** [comment]
삭제 완료했습니다

**Comment by gyuturn** [comment]
확인하였습니다.
